DataLayer\Entities\ApplicationLogTypes:
    type: entity
    table: application_log_types
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
